options(useFancyQuotes = FALSE)
cat("Welcome.\n")
cat("loading 10 packages")
library(tidyr)
library(dplyr)
library(foreign)
library(magrittr)
library(lubridate)
library(stringr)
library(data.table)
library(ggplot2)
library(scale)
library(zipcode)